app_name: certificates.orders.web.ch.gov.uk
group: web
weight: 990
# When we move static files to the CDN routes 3, and 4 will be removed
routes:
  1: /company/(.*)/orderable/certificates
  2: /company/(.*)/orderable/certificates/.*
  3: /orderable/certificates-assets
  4: /orderable/certificates-assets/.*
  5: /orderable/certificates
  6: /orderable/certificates/.*
  7: /company/(.*)/orderable/certified-copies
  8: /company/(.*)/orderable/certified-copies/.*
  9: /orderable/certified-copies
  10: /orderable/certified-copies/.*
  11: /company/(.*)/orderable/scan-upon-demand
  12: /company/(.*)/orderable/scan-upon-demand/.*
  13: /orderable/scan-upon-demand
  14: /orderable/scan-upon-demand/.