app_name: certificates.orders.web.ch.gov.uk
group: web
weight: 990
# When we move static files to the CDN routes 3, and 4 will be removed
routes:
  1: /company/(.*)/orderable/certificates
  2: /company/(.*)/orderable/certificates/.*
  3: /orderable/certificates-assets
  4: /orderable/certificates-assets/.*
  5: /orderable/certificates
  6: /orderable/certificates/.*
  7: /company/(.*)/orderable/certified-copies
  8: /company/(.*)/orderable/certified-copies/.*
  9: /orderable/certified-copies
  10: /orderable/certified-copies/.*
  11: /company/(.*)/orderable/missing-image-deliveries
  12: /company/(.*)/orderable/missing-image-deliveries/.*
  13: /orderable/missing-image-deliveries
  14: /orderable/missing-image-deliveries/.
  15: /company/(.*)/orderable/dissolved-certificates
  16: /company/(.*)/orderable/dissolved-certificates/.*
  17: /orderable/dissolved-certificates
  18: /orderable/dissolved-certificates/.*  
  19: /company/(.*)/orderable/llp-certificates
  20: /company/(.*)/orderable/llp-certificates/.*
  21: /orderable/llp-certificates
  22: /orderable/llp-certificates/.*
  23: /company/(.*)/orderable/lp-certificates
  24: /company/(.*)/orderable/lp-certificates/.*
  25: /orderable/lp-certificates
  26: /orderable/lp-certificates/.*